### ISSUE TITLE
Fails when trying to save word definitions.

### ISSUE THREAD

**Issue by mitigd** [nczempin/fltr#3]
**Problem**:
After adding a text for your selected language, then trying to define words it fails some sort of condition. After that the window becomes uncloseable and the definitions are never saved.

>Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at java.desktop/sun.awt.SunToolkit.getImageFromHash(SunToolkit.java:653)
        at java.desktop/sun.awt.SunToolkit.getImage(SunToolkit.java:689)
        at fltrpackage.Utilities.showYesNoQuestion(Utilities.java:640)
        at fltrpackage.TextFrameListener.windowClosing(TextFrameListener.java:377)
        at java.desktop/java.awt.Window.processWindowEvent(Window.java:2070)
        at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
        at java.desktop/java.awt.Window.processEvent(Window.java:2029)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

**Comment by nczempin** [comment]
ah yes, more problems with images.

as a quick fix, I will go through the entire codebase and try and find all the places where this could occur (and make sure it can't).

**Comment by nczempin** [comment]
medium term I'll want to get the broken icons actually working

**Comment by nczempin** [comment]
better robustness, so that a minor error like that doesn't take down the entire application, would also be a reasonable goal (no promises, though).

**Comment by ParaplegicRacehorse** [comment]
Just a quick update. Per the 0.8.10 change log in the user manual (see issue #1 ), all this was fixed in 0.8.10 or previous and a change to Java 1.8 happened. I have a lead on bytecode (maybe also source?) for 0.8.10.

**Comment by nczempin** [comment]
Hi @mitigd,

This NPE issue appears to be related to missing icon files when the application tries to display dialogs. I actually encountered and fixed a similar issue in this fork.

## Immediate Solutions

### Option 1: Use the Official Version
The original FLTR developers have resumed maintenance and released version 1.4.0 (June 2021):
- **Download**: https://sourceforge.net/projects/foreign-language-text-reader/
- **Website**: https://foreign-language-text-reader.sourceforge.io

While my analysis shows they haven't fixed this specific NPE issue in v1.4.0, they may have made other improvements that help.

### Option 2: Use This Fork with the Fix
This fork contains a fix for NPE issues related to missing icons (fixed in commit 7a60fdf). To use this version:

1. Build from source:
   ```bash
   javac -d bin -sourcepath src -cp lib/miglayout-4.0.jar src/fltrpackage/Application.java
   cp src/fltrpackage/icon128.png bin/fltrpackage/
   ```

2. Run with proper classpath:
   - Linux/Mac: `java -cp "bin:lib/miglayout-4.0.jar" fltrpackage.Application`
   - Windows: `java -cp "bin;lib/miglayout-4.0.jar" fltrpackage.Application`

### Option 3: Alternative GitHub Fork
Try magnus-ISU's fork which may have additional fixes:
- https://github.com/magnus-ISU/foreign-language-text-reader

## Technical Details

The NPE occurs in `Utilities.showYesNoQuestion()` when it tries to load an icon that doesn't exist or can't be found in the classpath. The fix involves proper null checking before attempting to use icon resources.

## Preventing the Issue

Make sure:
1. All resource files (especially icons) are properly included in your classpath
2. The application has proper permissions to read resource files
3. You're running from the correct directory with access to the resources

I hope this helps\! Let me know if you need any clarification on the build process or continue to experience issues.
